In [1]:
import pandas as pd
import json

In [6]:
with open('new_inventory_data.json') as f:
    data = json.load(f)

In [7]:
df = pd.DataFrame(data)
df

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,Shipping times,Shipping carriers,Shipping costs,Order details
0,Sports,7841,90.55,In Stock,55,4980.25,Female,701,6,7,2,UPS,5.61,"[{'Order date': '2022-12-18', 'Shipment date':..."
1,Home,9799,97.13,Out of Stock,82,7964.66,Other,702,1,5,2,UPS,10.14,"[{'Order date': '2023-06-03', 'Shipment date':..."
2,Sports,7732,51.78,Out of Stock,29,1501.62,Male,895,7,6,3,FedEx,9.91,"[{'Order date': '2022-11-11', 'Shipment date':..."
3,Sports,1205,98.01,In Stock,84,8232.84,Other,54,5,4,4,DHL,12.39,"[{'Order date': '2023-02-15', 'Shipment date':..."
4,Clothing,4407,55.64,Out of Stock,10,556.40,Female,641,7,7,5,DHL,7.10,"[{'Order date': '2023-04-18', 'Shipment date':..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,Clothing,1469,40.99,Out of Stock,21,860.79,Male,270,6,4,3,UPS,14.02,"[{'Order date': '2022-12-24', 'Shipment date':..."
296,Clothing,7958,66.03,In Stock,72,4754.16,Other,461,7,7,4,UPS,7.52,"[{'Order date': '2023-03-17', 'Shipment date':..."
297,Sports,7089,25.88,In Stock,94,2432.72,Other,450,5,1,3,DHL,16.99,"[{'Order date': '2023-06-14', 'Shipment date':..."
298,Home,8383,61.82,In Stock,13,803.66,Female,567,2,9,1,DHL,8.31,"[{'Order date': '2022-11-12', 'Shipment date':..."
299,Home,3059,94.34,In Stock,79,7452.86,Other,901,4,3,5,DHL,12.54,"[{'Order date': '2023-05-04', 'Shipment date':..."

In [ ]:
df_filtered = df[df['Order d'] == 0]
df_filtered